name: Secret Inventory Report

on:
  workflow_dispatch:

jobs:
  secret-inventory:
    runs-on: ubuntu-latest
    env:
      SOURCE_ORG: SOURCE_ORG
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verify GitHub CLI
        run: |
          gh --version

      - name: Generate Secret Inventory Report
        env:
          GH_SOURCE_PAT: ${{ secrets.GH_SOURCE_PAT }}
        run: |
          export GH_TOKEN=$GH_SOURCE_PAT
          echo "Repository,SecretNames" > secret_inventory_report.csv

          while read REPO
          do
            echo "Processing $REPO"

            SECRET_NAMES=$(gh secret list \
              --repo $SOURCE_ORG/$REPO \
              --json name \
              -q '.[].name' 2>/dev/null | paste -sd ";" -)

            if [ -z "$SECRET_NAMES" ]; then
              SECRET_NAMES="NO_SECRETS"
            fi

            echo "$REPO,\"$SECRET_NAMES\"" >> secret_inventory_report.csv

          done < secret_inventory_repos.txt

          echo "===== REPORT ====="
          cat secret_inventory_report.csv

      - name: Upload Report
        uses: actions/upload-artifact@v4
        with:
          name: secret-inventory-report
          path: secret_inventory_report.csv
